services:
  db:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5472:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
