// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: truncate.sql

package sqlc

import (
	"context"
)

const truncateAllTables = `-- name: TruncateAllTables :exec

SELECT 1
`

// TODO: restrict this to only tests using build tags
func (q *Queries) TruncateAllTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAllTables)
	return err
}
