// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlc

import (
	"context"
)

const demo = `-- name: Demo :one
SELECT 1 AS user
`

func (q *Queries) Demo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, demo)
	var user int32
	err := row.Scan(&user)
	return user, err
}
